// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8teUFzXvFrQaS1Qv3L21yKnPn1EoXIE',
    appId: '1:545977285611:web:2ce53003713420b3cbf7ae',
    messagingSenderId: '545977285611',
    projectId: 'punc-pi-2026',
    authDomain: 'punc-pi-2026.firebaseapp.com',
    storageBucket: 'punc-pi-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhY-tRMOxCIShYbrsCZAGhgSv0H0m7FbU',
    appId: '1:545977285611:android:d8988a341a4ff433cbf7ae',
    messagingSenderId: '545977285611',
    projectId: 'punc-pi-2026',
    storageBucket: 'punc-pi-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNYK6bMSdnkthLbyCNlXzIukimyB-KYM',
    appId: '1:545977285611:ios:b397734a2cbe71c7cbf7ae',
    messagingSenderId: '545977285611',
    projectId: 'punc-pi-2026',
    storageBucket: 'punc-pi-2026.firebasestorage.app',
    iosBundleId: 'com.example.punc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNYK6bMSdnkthLbyCNlXzIukimyB-KYM',
    appId: '1:545977285611:ios:b397734a2cbe71c7cbf7ae',
    messagingSenderId: '545977285611',
    projectId: 'punc-pi-2026',
    storageBucket: 'punc-pi-2026.firebasestorage.app',
    iosBundleId: 'com.example.punc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-8teUFzXvFrQaS1Qv3L21yKnPn1EoXIE',
    appId: '1:545977285611:web:ba3e8c743a11c1ddcbf7ae',
    messagingSenderId: '545977285611',
    projectId: 'punc-pi-2026',
    authDomain: 'punc-pi-2026.firebaseapp.com',
    storageBucket: 'punc-pi-2026.firebasestorage.app',
  );
}
